import random


characters = [
    {"name": "chris",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": False ,
    },
        {"name": "nick",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": False ,
    },
        {"name": "kyle",  
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    },
        {"name": "daniel",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": True ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": False ,
    },
        {"name": "rachael",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": True ,
    },
        {"name": "jake",
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "sarah",
    "ist_blond": False , 
    "hat_schwarzehaare": True ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": True ,
     },
             {"name": "emily",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": True ,
     },
             {"name": "andy",
    "ist_blond": False , 
    "hat_schwarzehaare": True ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "tyler",
    "ist_blond": False , 
    "hat_schwarzehaare": True ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "brandon",
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "James",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": True , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "zachary",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": True , 
    "hat_braunehaare": False ,
    "hat_rotehaare": True ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "Jon",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "william",
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "justin",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "joseph",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": True ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": False ,
     },
             {"name": "connor",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "alex",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": True , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": False ,
     },
             {"name": "ashley",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": True ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": True ,
     },
             {"name": "joshua",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
     },
             {"name": "matt",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
        },
]

fragen_liste = [
    "1. Ist die Person blond?",
    "2. Hat die Person schwarze Haare?",
    "3. Hat die Person weisse Haare?",
    "4. Hat die Person eine Glatze?",
    "5. Hat die Person braune Haare?",
    "6. Hat die Person rote Haare?",
    "7. Hat die Person einen Bart?",
    "8. Hat die Person braune Augen?",
    "9. Hat die Person blaue Augen?",
    "10. Ist die Person weiss?",
    "11. Hat die Person eine grosse Nase?",
    "12. Traegt die Person einen Hut?",
    "13. Traegt die Person eine Brille?",
    "14. Traegt die Person Ohrringe?"]

print ("#Willkommen zum 'Wer ist es?' Spiel!#")
character = random.choice(characters)
print ("# Hier siehtst du ein bild mit allen Charackteren #")
print ("# Der bot wird einen von diesen charackteren ausgewählt haben und du musst versuchen ihn zu eraten mithilfe von diesen fargen #")
print (fragen_liste)
print ("# Gib bitte nur die zahlen vor den fragen ein um diese zu stallen #")
i=0
i=int(input("# Was ist deine erste frage #"))
i =-1
for u in range (len(character)):
        if u == i:
                jn = character[u]
                if jn == False:
                        print (ne)
                else:
                        print (joa)
