from PIL import Image


characters = [
    {"name": "chris",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/chris.jpg"
    },
        {"name": "nick",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": False ,
    "foto": "./ilder/nick.jpg"
    },
        {"name": "kyle",  
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/kyle.jpg"
    },
        {"name": "daniel",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": True ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/daniel.jpg"
    },
        {"name": "rachael",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": True ,
    "foto": "./ilder/rachael.jpg"
    },
        {"name": "jake",
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/jake.jpg"
     },
        {"name": "sarah",
    "ist_blond": False , 
    "hat_schwarzehaare": True ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": True ,
    "foto": "./ilder/sarah.jpg"
     },
        {"name": "emily",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": True ,
    "foto": "./ilder/emily.jpg"
     },
        {"name": "andy",
    "ist_blond": False , 
    "hat_schwarzehaare": True ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/andy.jpg"
     },
        {"name": "tyler",
    "ist_blond": False , 
    "hat_schwarzehaare": True ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/tyler.jpg"
     },
        {"name": "brandon",
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/brandon.jpg"
     },
        {"name": "James",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": True , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/james.jpg"
     },
        {"name": "zachary",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": True , 
    "hat_braunehaare": False ,
    "hat_rotehaare": True ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/zachary.jpg"
     },
        {"name": "Jon",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/Jon.jpg"
     },
        {"name": "william",
    "ist_blond": True , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/william.jpg"
     },
        {"name": "justin",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/justin.jpg"
     },
        {"name": "joseph",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": True ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": True ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": False ,
    "foto": "./ilder/joseph.jpg"
     },
        {"name": "connor",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": True ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": False ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/connor.jpg"
     },
        {"name": "alex",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": True , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": True,
    "hat_ohrringe": False ,
    "foto": "./ilder/alex.jpg"
     },
        {"name": "ashley",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": False , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": True ,
    "hat_bart": False ,
    "hat_brauneaugen": False ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": True,
    "hat_brille": False,
    "hat_ohrringe": True ,
    "foto": "./ilder/ashley.jpg"
     },
        {"name": "joshua",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": True ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": True ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/joshua.jpg"
     },
        {"name": "matt",
    "ist_blond": False , 
    "hat_schwarzehaare": False ,
    "hat_Weissehaare": True , 
    "hat_glatze": False , 
    "hat_braunehaare": False ,
    "hat_rotehaare": False ,
    "hat_bart": False ,
    "hat_brauneaugen": True ,
    "hat_blaueaugen": False ,
    "ist_weiss": True ,
    "hat_grosse_nase": False ,
    "hat_hut": False,
    "hat_brille": False,
    "hat_ohrringe": False ,
    "foto": "./ilder/matt.jpg"
        },
]

fotos = [
    "./ilder/chris.jpg",
    "./ilder/nick.jpg",
    "./ilder/kyle.jpg",
    "./ilder/daniel.jpg",
    "./ilder/rachael.jpg",
    "./ilder/jake.jpg",
    "./ilder/sarah.jpg",
    "./ilder/emily.jpg",
    "./ilder/andy.jpg",
    "./ilder/tyler.jpg",
    "./ilder/brandon.jpg",
    "./ilder/James.jpg",
    "./ilder/zachary.jpg",
    "./ilder/Jon.jpg",
    "./ilder/william.jpg",
    "./ilder/justin.jpg",
    "./ilder/joseph.jpg",
    "./ilder/connor.jpg",
    "./ilder/alex.jpg",
    "./ilder/ashley.jpg",
    "./ilder/joshua.jpg",
    "./ilder/matt.jpg",
]

ausschließen=0

for i in range(len(characters)):
    print(characters[i]["name"])
    print(i)

while ausschließen != "nein":
    ausschließen = input("# Möchtest du einen Charakter ausschließen? Wenn ja dann schreibe den namen #")
    for nameausschließen in range(len (characters)):
        if characters[nameausschließen]["name"] == ausschließen:
            characters.pop (nameausschließen)
            print (f"# Du hast {ausschließen} ausgeschlossen #")
            break
    ausschließen = input("# Möchtest du einen weiteren Charakter ausschließen? Wenn ja dann schreibe den namen, wenn nein schreibe 'nein' #")


for foto_offnen in range(len(characters)):
    img = Image.open(characters[foto_offnen]["foto"])
    img.show()

for i in range(len(characters)):
    print(characters[i]["name"])
    print(i)